### ISSUE TITLE
Generating trainable/predictable data

### ISSUE THREAD

**Issue by ghost** [omegahh/DeepHiC#11]
Hello, 

I was following the steps in the tutorial for generating trainable/predictable data of the DeepHiC : 

python data_generate.py -hr 10kb -lr 40kb -s train -chunk 40 -stride 40 -bound 201 -scale 1 -c /home/DeepHiC-master/raw/GM12878 -lrc 100

I received the following error :

Traceback (most recent call last):
  File "data_generate.py", line 75, in <module>
    data = np.concatenate([r.get()[1] for r in results])
  File "data_generate.py", line 75, in <listcomp>
    data = np.concatenate([r.get()[1] for r in results])
  File "/miniconda3/envs/deephic/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: non-empty 3D or 4D (batch mode) tensor expected for input

**Comment by gayahaber** [comment]
@omegahh can you help me to solve this error.

**Comment by omegahh** [comment]
Sorry for the delay. It seems like something wrong with your input data? I am not sure. It would be better if you could offer me the data (or part of them). I will try to run it by myself and help finding the solution.

**Comment by gayahaber** [comment]
Hello,

You can find attached my data.

Regards

Gaya EL HABER

----- Mail original -----
De: "Omega Alpha" ***@***.***>
À: "omegahh/DeepHiC" ***@***.***>
Cc: "gaya el-haber" ***@***.***>, "Author" ***@***.***>
Envoyé: Mercredi 24 Mai 2023 04:39:51
Objet: Re: [omegahh/DeepHiC] Generating trainable/predictable data (Issue #11)

Sorry for the delay. It seems like something wrong with your input data? I am not sure. It would be better if you could offer me the data (or part of them). I will try to run it by myself and help finding the solution.

**Comment by gayahaber** [comment]
Okay no problem can you give your email to send you my input data.

**Comment by omegahh** [comment]
omeganju@gmail.com
